import { createSlice } from '@reduxjs/toolkit';

const initialState = {
   userName: 'Unregistered',
   isLogin: false,
};

export const loginSlice = createSlice({
   name: 'login',
   initialState,
   // The `reducers` field lets us define reducers and generate associated actions
   reducers: {
      logIn: (state, action) => {
         state.isLogin = true;
         state.userName = action.payload;
      },
      logOut: (state) => {
         state.isLogin = false;
         state.userName = 'Unregistered';
      },
      // Use the PayloadAction type to declare the contents of `action.payload`
      incrementByAmount: (state, action) => {
         state.value += action.payload;
      },
   },
   // The `extraReducers` field lets the slice handle actions defined elsewhere,
   // including actions generated by createAsyncThunk or in other slices.
});

export const { logIn, logOut } = loginSlice.actions;
export const selectIsLogin = (state) => state.login.isLogin;
export const selectUserName = (state) => state.login.userName;

export default loginSlice.reducer;
